Implement the prototype for BbML
LPTK/mlscript pull request #9
Opened 2024-07-28 12:18 UTC by NeilKleistGao

In this PR:
- Implemented inference and constraints solving algorithm
- Extended `Tree` and `Term` and updated related logics of parsing and elaborating
- Added related test cases and updated `DiffMaker`
- Added pretty printer and simplfier for BbML

TODO (or in next PR):
- [ ] Handle all warnings
- [ ] Add qq term type parameter

2024-07-30 10:19 UTC, LPTK commented
There's no need to handle all warnings for now. We'll look into this once we're ready to settle on final designs in hkmc2 and make it production-ready.

2024-07-30 10:23 UTC, LPTK commented
Are there any tests of the `case` feature and how it allows pattern-matching on classes?

2024-07-30 12:04 UTC, NeilKleistGao commented
> Are there any tests of the `case` feature and how it allows pattern-matching on classes?

So far the `case` expressions are only for the existing test cases for quasiquotes so it doesn't support class pattern matching (can be added later).

2024-07-31 03:57 UTC, LPTK commented
> So far the `case` expressions are only for the existing test cases for quasiquotes so it doesn't support class pattern matching (can be added later).

Ah ok. Yeah, we should definitely add support for that like in the paper, but in a future PR.

2024-08-02 10:06 UTC, LPTK approved these changes
Ok, LGTM, although I didn't review everything in detail. But let's get it merged into this WIP branch anyway as I want to make progress ASAP. Please address the couple of comments first, though.

2024-08-02 10:06 UTC, LPTK commented on hkmc2/shared/src/main/scala/hkmc2/syntax/Parser.scala
> +              if id.name == "true" || id.name == "false" then // * true & false are expressions, allow parsing `if true is Bool then ...`
But why aren't these normal parse rules? Instead of hard-coding them here!

2024-08-02 10:06 UTC, LPTK commented on hkmc2/shared/src/main/scala/hkmc2/syntax/Parser.scala
> +      val res = rec(toks, S(loc), "forall qualifiers").concludeWith(_.expr(0))
```suggestion
      val res = rec(toks, S(loc), "type parameters").concludeWith(_.expr(0))
```

2024-08-02 10:06 UTC, LPTK commented on hkmc2/shared/src/main/scala/hkmc2/bbml/PrettyPrinter.scala
> +  private def collectBounds(ty: GeneralType)(using cache: TVCache): List[Bound] = ty match
It seems this would be more concisely implemented using `TypeTraverser`.

2024-08-03 05:07 UTC, LPTK commented
I still want to merge this ASAP, but it does have serious problems to solve later. I've documented them in https://github.com/hkust-taco/scope-safety-paper/issues/4.

2024-08-03 15:38 UTC, LPTK requested changes

2024-08-03 15:38 UTC, LPTK commented on hkmc2/shared/src/main/scala/hkmc2/syntax/ParseRule.scala
> +    ),
???

Are you really special-casing all expressions of the form `true and ...`, `true or ...` etc.?

This is inane. Come on, you can do better 😕

2024-08-03 15:38 UTC, LPTK commented on hkmc2/shared/src/main/scala/hkmc2/syntax/Parser.scala
> +        case S(kw) =>
Keywords are not expected to be handled here! This `expr` function is only for simple expressions not starting with a keyword. This `S(kw)` case should yield an error.

2024-08-05 04:05 UTC, LPTK approved these changes

2024-08-05 04:17 UTC, merged